// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: noble/globalfee/v1/tx.proto

package globalfeev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdateGasPrices_FullMethodName      = "/noble.globalfee.v1.Msg/UpdateGasPrices"
	Msg_UpdateBypassMessages_FullMethodName = "/noble.globalfee.v1.Msg/UpdateBypassMessages"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	UpdateGasPrices(ctx context.Context, in *MsgUpdateGasPrices, opts ...grpc.CallOption) (*MsgUpdateGasPricesResponse, error)
	UpdateBypassMessages(ctx context.Context, in *MsgUpdateBypassMessages, opts ...grpc.CallOption) (*MsgUpdateBypassMessagesResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateGasPrices(ctx context.Context, in *MsgUpdateGasPrices, opts ...grpc.CallOption) (*MsgUpdateGasPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateGasPricesResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateGasPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBypassMessages(ctx context.Context, in *MsgUpdateBypassMessages, opts ...grpc.CallOption) (*MsgUpdateBypassMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateBypassMessagesResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateBypassMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
type MsgServer interface {
	UpdateGasPrices(context.Context, *MsgUpdateGasPrices) (*MsgUpdateGasPricesResponse, error)
	UpdateBypassMessages(context.Context, *MsgUpdateBypassMessages) (*MsgUpdateBypassMessagesResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdateGasPrices(context.Context, *MsgUpdateGasPrices) (*MsgUpdateGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGasPrices not implemented")
}
func (UnimplementedMsgServer) UpdateBypassMessages(context.Context, *MsgUpdateBypassMessages) (*MsgUpdateBypassMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBypassMessages not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateGasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateGasPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateGasPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGasPrices(ctx, req.(*MsgUpdateGasPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBypassMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBypassMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBypassMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateBypassMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBypassMessages(ctx, req.(*MsgUpdateBypassMessages))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noble.globalfee.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateGasPrices",
			Handler:    _Msg_UpdateGasPrices_Handler,
		},
		{
			MethodName: "UpdateBypassMessages",
			Handler:    _Msg_UpdateBypassMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/globalfee/v1/tx.proto",
}
