// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/globalfee/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the genesis state of the GlobalFee module.
type GenesisState struct {
	// gas_prices defines a list of gas prices to be used when checking a transaction's fee.
	GasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=gas_prices,json=gasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"gas_prices"`
	// bypass_messages defines a list of message types that can bypass the required fees.
	BypassMessages []string `protobuf:"bytes,2,rep,name=bypass_messages,json=bypassMessages,proto3" json:"bypass_messages,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_04b3af92b6d80f0c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.GasPrices
	}
	return nil
}

func (m *GenesisState) GetBypassMessages() []string {
	if m != nil {
		return m.BypassMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "noble.globalfee.v1.GenesisState")
}

func init() { proto.RegisterFile("noble/globalfee/v1/genesis.proto", fileDescriptor_04b3af92b6d80f0c) }

var fileDescriptor_04b3af92b6d80f0c = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xc1, 0x4a, 0x33, 0x31,
	0x18, 0xdc, 0xfc, 0x85, 0x1f, 0xba, 0x8a, 0xe2, 0xe2, 0xa1, 0x16, 0x49, 0x8b, 0x97, 0x16, 0xa5,
	0x09, 0xd5, 0x27, 0xb0, 0x16, 0x3d, 0x09, 0x52, 0x6f, 0x5e, 0x4a, 0xb2, 0x7e, 0xc6, 0x60, 0x77,
	0x53, 0xfc, 0x62, 0xa1, 0x67, 0x5f, 0xc0, 0xc7, 0x10, 0x4f, 0x1e, 0xbc, 0x7a, 0xef, 0xb1, 0x78,
	0xf2, 0xa4, 0xd2, 0x3d, 0xf8, 0x1a, 0xb2, 0x49, 0x94, 0x5e, 0x76, 0xf3, 0xcd, 0x4c, 0x66, 0x86,
	0x2f, 0x71, 0x33, 0x37, 0x72, 0x04, 0x5c, 0x8d, 0x8c, 0x14, 0xa3, 0x2b, 0x00, 0x3e, 0xe9, 0x72,
	0x05, 0x39, 0xa0, 0x46, 0x36, 0xbe, 0x35, 0xd6, 0x24, 0x89, 0x53, 0xb0, 0x3f, 0x05, 0x9b, 0x74,
	0xeb, 0x1b, 0x22, 0xd3, 0xb9, 0xe1, 0xee, 0xeb, 0x65, 0x75, 0x9a, 0x1a, 0xcc, 0x0c, 0x72, 0x29,
	0xb0, 0x34, 0x91, 0x60, 0x45, 0x97, 0xa7, 0x46, 0xe7, 0x81, 0xdf, 0xf2, 0xfc, 0xd0, 0x4d, 0xdc,
	0x0f, 0x81, 0xda, 0x54, 0x46, 0x19, 0x8f, 0x97, 0x27, 0x8f, 0xee, 0xbc, 0x92, 0x78, 0xf5, 0xc4,
	0x37, 0x39, 0xb7, 0xc2, 0x42, 0x72, 0x4f, 0xe2, 0x58, 0x89, 0xd2, 0x41, 0xa7, 0x80, 0x35, 0xd2,
	0xac, 0xb4, 0x57, 0xf6, 0xb7, 0x59, 0xb0, 0x2a, 0x73, 0x59, 0xc8, 0x65, 0x7d, 0x48, 0x8f, 0x8c,
	0xce, 0x7b, 0xc7, 0xb3, 0x8f, 0x46, 0xf4, 0xf4, 0xd9, 0xd8, 0x53, 0xda, 0x5e, 0xdf, 0x49, 0x96,
	0x9a, 0x2c, 0x44, 0x87, 0x5f, 0x07, 0x2f, 0x6f, 0xb8, 0x9d, 0x8e, 0x01, 0x7f, 0xef, 0xe0, 0xdb,
	0x4b, 0x27, 0x0e, 0x9e, 0x7d, 0x48, 0x1f, 0xbf, 0x9f, 0x77, 0xc9, 0xa0, 0xaa, 0x04, 0x9e, 0xb9,
	0xd8, 0xa4, 0x15, 0xaf, 0xcb, 0xe9, 0x58, 0x20, 0x0e, 0x33, 0x40, 0x14, 0x0a, 0xb0, 0xf6, 0xaf,
	0x59, 0x69, 0x57, 0x07, 0x6b, 0x1e, 0x3e, 0x0d, 0x68, 0xef, 0x70, 0xb6, 0xa0, 0x64, 0xbe, 0xa0,
	0xe4, 0x6b, 0x41, 0xc9, 0x43, 0x41, 0xa3, 0x79, 0x41, 0xa3, 0xf7, 0x82, 0x46, 0x17, 0xad, 0xa5,
	0x36, 0x6e, 0xb9, 0x1d, 0x81, 0x08, 0x16, 0x97, 0x5e, 0xc1, 0x55, 0x92, 0xff, 0xdd, 0x26, 0x0e,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x5b, 0x7e, 0xf7, 0xa5, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BypassMessages) > 0 {
		for iNdEx := len(m.BypassMessages) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BypassMessages[iNdEx])
			copy(dAtA[i:], m.BypassMessages[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.BypassMessages[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.GasPrices) > 0 {
		for iNdEx := len(m.GasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for _, e := range m.GasPrices {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BypassMessages) > 0 {
		for _, s := range m.BypassMessages {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPrices = append(m.GasPrices, types.DecCoin{})
			if err := m.GasPrices[len(m.GasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BypassMessages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BypassMessages = append(m.BypassMessages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
