// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: noble/globalfee/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateGasPrices is the request of the UpdateGasPrices action.
type MsgUpdateGasPrices struct {
	Signer    string                                      `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	GasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,2,rep,name=gas_prices,json=gasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"gas_prices"`
}

func (m *MsgUpdateGasPrices) Reset()         { *m = MsgUpdateGasPrices{} }
func (m *MsgUpdateGasPrices) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateGasPrices) ProtoMessage()    {}
func (*MsgUpdateGasPrices) Descriptor() ([]byte, []int) {
	return fileDescriptor_091175487d587c0b, []int{0}
}
func (m *MsgUpdateGasPrices) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateGasPrices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateGasPrices.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateGasPrices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateGasPrices.Merge(m, src)
}
func (m *MsgUpdateGasPrices) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateGasPrices) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateGasPrices.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateGasPrices proto.InternalMessageInfo

// MsgUpdateGasPricesResponse is the response of the UpdateGasPrices action.
type MsgUpdateGasPricesResponse struct {
}

func (m *MsgUpdateGasPricesResponse) Reset()         { *m = MsgUpdateGasPricesResponse{} }
func (m *MsgUpdateGasPricesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateGasPricesResponse) ProtoMessage()    {}
func (*MsgUpdateGasPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091175487d587c0b, []int{1}
}
func (m *MsgUpdateGasPricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateGasPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateGasPricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateGasPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateGasPricesResponse.Merge(m, src)
}
func (m *MsgUpdateGasPricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateGasPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateGasPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateGasPricesResponse proto.InternalMessageInfo

// MsgUpdateBypassMessages is the request of the UpdateBypassMessages action.
type MsgUpdateBypassMessages struct {
	Signer         string   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	BypassMessages []string `protobuf:"bytes,2,rep,name=bypass_messages,json=bypassMessages,proto3" json:"bypass_messages,omitempty"`
}

func (m *MsgUpdateBypassMessages) Reset()         { *m = MsgUpdateBypassMessages{} }
func (m *MsgUpdateBypassMessages) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBypassMessages) ProtoMessage()    {}
func (*MsgUpdateBypassMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_091175487d587c0b, []int{2}
}
func (m *MsgUpdateBypassMessages) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBypassMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBypassMessages.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBypassMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBypassMessages.Merge(m, src)
}
func (m *MsgUpdateBypassMessages) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBypassMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBypassMessages.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBypassMessages proto.InternalMessageInfo

// MsgUpdateBypassMessagesResponse is the response of the UpdateBypassMessages action.
type MsgUpdateBypassMessagesResponse struct {
}

func (m *MsgUpdateBypassMessagesResponse) Reset()         { *m = MsgUpdateBypassMessagesResponse{} }
func (m *MsgUpdateBypassMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBypassMessagesResponse) ProtoMessage()    {}
func (*MsgUpdateBypassMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_091175487d587c0b, []int{3}
}
func (m *MsgUpdateBypassMessagesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBypassMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBypassMessagesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBypassMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBypassMessagesResponse.Merge(m, src)
}
func (m *MsgUpdateBypassMessagesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBypassMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBypassMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBypassMessagesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateGasPrices)(nil), "noble.globalfee.v1.MsgUpdateGasPrices")
	proto.RegisterType((*MsgUpdateGasPricesResponse)(nil), "noble.globalfee.v1.MsgUpdateGasPricesResponse")
	proto.RegisterType((*MsgUpdateBypassMessages)(nil), "noble.globalfee.v1.MsgUpdateBypassMessages")
	proto.RegisterType((*MsgUpdateBypassMessagesResponse)(nil), "noble.globalfee.v1.MsgUpdateBypassMessagesResponse")
}

func init() { proto.RegisterFile("noble/globalfee/v1/tx.proto", fileDescriptor_091175487d587c0b) }

var fileDescriptor_091175487d587c0b = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xde, 0x69, 0xb1, 0x90, 0x11, 0x2c, 0x2e, 0x81, 0xc6, 0xb5, 0xec, 0xd6, 0x20, 0xb6, 0xa4,
	0x64, 0xd6, 0xb4, 0x07, 0xa1, 0x78, 0x69, 0x2c, 0x7a, 0x0a, 0x48, 0xc4, 0x8b, 0x97, 0x32, 0xb3,
	0x19, 0xc7, 0xc1, 0xec, 0xce, 0xb2, 0x6f, 0x2c, 0xed, 0x4d, 0x14, 0x41, 0x3c, 0xf9, 0x13, 0x7a,
	0x14, 0x4f, 0x41, 0xfa, 0x23, 0x7a, 0x2c, 0x3d, 0x79, 0x52, 0x49, 0x0e, 0xf1, 0xea, 0x3f, 0x90,
	0x9d, 0x9d, 0x2d, 0x4d, 0xd2, 0x8a, 0x7a, 0x49, 0x76, 0xe6, 0x7b, 0xef, 0x7b, 0xef, 0xfb, 0xf6,
	0x5b, 0x7c, 0x33, 0x51, 0xac, 0xcf, 0x43, 0xd1, 0x57, 0x8c, 0xf6, 0x9f, 0x73, 0x1e, 0xee, 0xb5,
	0x42, 0xbd, 0x4f, 0xd2, 0x4c, 0x69, 0xe5, 0xba, 0x06, 0x24, 0x67, 0x20, 0xd9, 0x6b, 0x79, 0xd7,
	0x69, 0x2c, 0x13, 0x15, 0x9a, 0xdf, 0xa2, 0xcc, 0xf3, 0x23, 0x05, 0xb1, 0x82, 0x90, 0x51, 0xc8,
	0xfb, 0x19, 0xd7, 0xb4, 0x15, 0x46, 0x4a, 0x26, 0x16, 0x5f, 0xb2, 0x78, 0x0c, 0x22, 0xa7, 0x8f,
	0x41, 0x58, 0xe0, 0x46, 0x01, 0xec, 0x9a, 0x53, 0x58, 0x1c, 0x2c, 0x54, 0x15, 0x4a, 0xa8, 0xe2,
	0x3e, 0x7f, 0x2a, 0x6e, 0xeb, 0xef, 0xe6, 0xb0, 0xdb, 0x01, 0xf1, 0x34, 0xed, 0x51, 0xcd, 0x1f,
	0x51, 0x78, 0x9c, 0xc9, 0x88, 0x83, 0x7b, 0x17, 0x2f, 0x80, 0x14, 0x09, 0xcf, 0x6a, 0x68, 0x05,
	0xad, 0x55, 0xda, 0xb5, 0xd3, 0xa3, 0x66, 0xd5, 0xd2, 0x6d, 0xf7, 0x7a, 0x19, 0x07, 0x78, 0xa2,
	0x33, 0x99, 0x88, 0xae, 0xad, 0x73, 0xdf, 0x22, 0x8c, 0x05, 0xcd, 0x27, 0xe7, 0x04, 0xb5, 0xb9,
	0x95, 0xf9, 0xb5, 0xab, 0x1b, 0xcb, 0xc4, 0xf6, 0xe4, 0x42, 0x88, 0x15, 0x42, 0x76, 0x78, 0xf4,
	0x40, 0xc9, 0xa4, 0xfd, 0xf0, 0xf8, 0x5b, 0xe0, 0x7c, 0xfe, 0x1e, 0xac, 0x0b, 0xa9, 0x5f, 0xbc,
	0x62, 0x24, 0x52, 0xb1, 0x5d, 0xd9, 0xfe, 0x35, 0xa1, 0xf7, 0x32, 0xd4, 0x07, 0x29, 0x87, 0xb2,
	0x07, 0x4e, 0x8f, 0x9a, 0xd8, 0x72, 0xee, 0xf0, 0xe8, 0xd3, 0x78, 0xd0, 0x40, 0xdd, 0x8a, 0x28,
	0xf7, 0xde, 0xba, 0xf7, 0xfe, 0x30, 0x70, 0x7e, 0x1e, 0x06, 0xce, 0x9b, 0xf1, 0xa0, 0x61, 0x57,
	0xfb, 0x30, 0x1e, 0x34, 0x82, 0xe9, 0x97, 0x32, 0x25, 0xb8, 0xbe, 0x8c, 0xbd, 0x59, 0x1b, 0xba,
	0x1c, 0x52, 0x95, 0x00, 0xaf, 0x7f, 0x41, 0x78, 0xe9, 0x0c, 0x6e, 0x1f, 0xa4, 0x14, 0xa0, 0xc3,
	0x01, 0xa8, 0xf8, 0x2f, 0xab, 0x56, 0xf1, 0x22, 0x33, 0x1c, 0xbb, 0xb1, 0x25, 0x31, 0x76, 0x55,
	0xba, 0xd7, 0xd8, 0x04, 0xf5, 0xd6, 0xfd, 0x4b, 0xd4, 0xdc, 0xbe, 0x58, 0xcd, 0xe4, 0x62, 0xf5,
	0x5b, 0x38, 0xb8, 0x64, 0xe7, 0x52, 0xd7, 0xc6, 0x2f, 0x84, 0xe7, 0x3b, 0x20, 0x5c, 0x89, 0x17,
	0xa7, 0x13, 0x70, 0x87, 0xcc, 0x46, 0x95, 0xcc, 0x5a, 0xe4, 0x91, 0xbf, 0xab, 0x2b, 0x47, 0xba,
	0xfb, 0xb8, 0x7a, 0xa1, 0x8d, 0xeb, 0x7f, 0xe4, 0x99, 0x2c, 0xf6, 0x36, 0xff, 0xa1, 0xb8, 0x9c,
	0xec, 0x5d, 0x79, 0x9d, 0xa7, 0xa5, 0xbd, 0x7d, 0x3c, 0xf4, 0xd1, 0xc9, 0xd0, 0x47, 0x3f, 0x86,
	0x3e, 0xfa, 0x38, 0xf2, 0x9d, 0x93, 0x91, 0xef, 0x7c, 0x1d, 0xf9, 0xce, 0xb3, 0xd5, 0x73, 0x39,
	0x34, 0xfc, 0x4d, 0x0a, 0xc0, 0x35, 0x9c, 0x33, 0xda, 0x84, 0x91, 0x2d, 0x98, 0x6f, 0x67, 0xf3,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x06, 0x23, 0x6e, 0xeb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateGasPrices(ctx context.Context, in *MsgUpdateGasPrices, opts ...grpc.CallOption) (*MsgUpdateGasPricesResponse, error)
	UpdateBypassMessages(ctx context.Context, in *MsgUpdateBypassMessages, opts ...grpc.CallOption) (*MsgUpdateBypassMessagesResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateGasPrices(ctx context.Context, in *MsgUpdateGasPrices, opts ...grpc.CallOption) (*MsgUpdateGasPricesResponse, error) {
	out := new(MsgUpdateGasPricesResponse)
	err := c.cc.Invoke(ctx, "/noble.globalfee.v1.Msg/UpdateGasPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBypassMessages(ctx context.Context, in *MsgUpdateBypassMessages, opts ...grpc.CallOption) (*MsgUpdateBypassMessagesResponse, error) {
	out := new(MsgUpdateBypassMessagesResponse)
	err := c.cc.Invoke(ctx, "/noble.globalfee.v1.Msg/UpdateBypassMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateGasPrices(context.Context, *MsgUpdateGasPrices) (*MsgUpdateGasPricesResponse, error)
	UpdateBypassMessages(context.Context, *MsgUpdateBypassMessages) (*MsgUpdateBypassMessagesResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateGasPrices(ctx context.Context, req *MsgUpdateGasPrices) (*MsgUpdateGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGasPrices not implemented")
}
func (*UnimplementedMsgServer) UpdateBypassMessages(ctx context.Context, req *MsgUpdateBypassMessages) (*MsgUpdateBypassMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBypassMessages not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateGasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateGasPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.globalfee.v1.Msg/UpdateGasPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGasPrices(ctx, req.(*MsgUpdateGasPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBypassMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBypassMessages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBypassMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noble.globalfee.v1.Msg/UpdateBypassMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBypassMessages(ctx, req.(*MsgUpdateBypassMessages))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noble.globalfee.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateGasPrices",
			Handler:    _Msg_UpdateGasPrices_Handler,
		},
		{
			MethodName: "UpdateBypassMessages",
			Handler:    _Msg_UpdateBypassMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noble/globalfee/v1/tx.proto",
}

func (m *MsgUpdateGasPrices) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateGasPrices) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateGasPrices) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GasPrices) > 0 {
		for iNdEx := len(m.GasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateGasPricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateGasPricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateGasPricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBypassMessages) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBypassMessages) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBypassMessages) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BypassMessages) > 0 {
		for iNdEx := len(m.BypassMessages) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BypassMessages[iNdEx])
			copy(dAtA[i:], m.BypassMessages[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.BypassMessages[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBypassMessagesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBypassMessagesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBypassMessagesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateGasPrices) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.GasPrices) > 0 {
		for _, e := range m.GasPrices {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateGasPricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateBypassMessages) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.BypassMessages) > 0 {
		for _, s := range m.BypassMessages {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateBypassMessagesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateGasPrices) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateGasPrices: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateGasPrices: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPrices = append(m.GasPrices, types.DecCoin{})
			if err := m.GasPrices[len(m.GasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateGasPricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateGasPricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateGasPricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBypassMessages) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBypassMessages: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBypassMessages: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BypassMessages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BypassMessages = append(m.BypassMessages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBypassMessagesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBypassMessagesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBypassMessagesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
